# Reading images and convertign them to numpy 

In [3]:
import cv2
import numpy as np
import pandas as pd


In [4]:
img_g = cv2.imread("smallgray.png",0)
img_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
imagew=cv2.imread("w.jpg",0)
imagew

array([[112, 110, 101, ...,  42,  38,  31],
       [111, 106,  96, ...,  59,  59,  57],
       [102,  95,  87, ...,  69,  73,  75],
       ...,
       [ 68,  67,  65, ...,  57,  62,  69],
       [ 86,  78,  64, ...,  57,  59,  63],
       [ 93,  79,  61, ...,  66,  64,  64]], dtype=uint8)

In [6]:
cv2.imwrite("grey.jpg",imagew)

False

In [7]:
imagew

array([[112, 110, 101, ...,  42,  38,  31],
       [111, 106,  96, ...,  59,  59,  57],
       [102,  95,  87, ...,  69,  73,  75],
       ...,
       [ 68,  67,  65, ...,  57,  62,  69],
       [ 86,  78,  64, ...,  57,  59,  63],
       [ 93,  79,  61, ...,  66,  64,  64]], dtype=uint8)

In [8]:
print("Good work on images")

Good work on images
